// <auto-generated />
namespace Rozabto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Volume : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Volume));

        string IMigrationMetadata.Id
        {
            get { return "201903301352252_Volume"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
